BurgerMenu
Larik7/GooseTrack-Frontend pull request #30
Opened 2023-06-26 21:10 UTC by Anton-Logvinenko

2023-06-26 23:07 UTC, Larik7 requested changes
3(три) файли з конфліктом: 
src/components/Header/Header.jsx
src/components/SideBar/sideBar.module.css
src/pages/MainLayout/MainLayout.jsx
краще локально виправ у себе. Якщо-що я можу виправити, але в мене деякі питання є по файлу MainLayout.jsx

2023-06-27 12:21 UTC, internet-user-0 requested changes
треба виправити

2023-06-27 12:21 UTC, internet-user-0 commented on src/components/Header/Header.jsx
> +        <button className={css.burgerMenu} onClick={handlerMenu}> <RxHamburgerMenu size={32}/></button>
цю кнопку svg взагалі не видно в розмітці, і вона не працює

2023-06-27 12:45 UTC, internet-user-0 approved these changes
конфлікти прбрав, все працює

2023-06-27 15:16 UTC, Larik7 approved these changes

2023-06-27 15:16 UTC, merged