add feedbackBtn
Larik7/GooseTrack-Frontend pull request #32
Opened 2023-06-27 13:16 UTC by Valeriia2306

Please check!

2023-06-27 15:18 UTC, internet-user-0 commented on src/components/AddFeedbackBtn/AddFeedbackBtn.jsx
> +const AddFeedbackBtn = () => {
передай пропсом стилы з Header  const AddFeedbackBtn = ( `{feedbackBtn}` ) => {

2023-06-27 15:19 UTC, internet-user-0 commented on src/components/AddFeedbackBtn/AddFeedbackBtn.jsx
> +      <button className={css.feedbackBtn} onClick={handleButtonClick}>
стилі без імпорту, буде помилка потім пропсами добавиш стилі   className={ `feedbackBtn` }

2023-06-27 15:20 UTC, internet-user-0 commented on src/components/AddFeedbackBtn/AddFeedbackBtn.jsx
> +export default AddFeedbackBtn;
ми договорювалися на іменовані експорти `export` const AddFeedbackBtn = () => {

2023-06-27 15:21 UTC, internet-user-0 requested changes
виправ будь ласка

2023-06-27 18:15 UTC, Valeriia2306 commented
тепер вірно?

2023-06-28 08:06 UTC, Valeriia2306 commented
перевірте будь ласка

2023-06-28 12:46 UTC, Larik7 approved these changes
ок

2023-06-28 12:54 UTC, merged